begin;
create extension if not exists pgtap with schema extensions;
select no_plan();
insert into auth.users(id,email,raw_user_meta_data) values ('c3000000-0000-4000-8000-000000000001','c3@example.invalid','{"terms_version":"ca-launch-v1"}');
select set_config('request.jwt.claims','{"sub":"c3000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$update public.profiles set display_name='Unchecked' where id=auth.uid()$$,'42501','policy_acknowledgement_required','missing acknowledgement blocks direct profile write');
select throws_ok($$insert into public.applications(job_id,seeker_id) values('bbbbbbbb-0000-0000-0000-000000000001',auth.uid())$$,'42501','policy_acknowledgement_required','direct application insert cannot skip account acknowledgement');
select throws_ok($$select public.acknowledge_policies('ca-launch-v1',false,'ca-launch-v1',true)$$,'42501',null,'unchecked terms rejected');
select throws_ok($$select public.acknowledge_policies('old',true,'ca-launch-v1',true)$$,'42501',null,'old version rejected');
select throws_ok($$select public.acknowledge_policies('ca-launch-v1',true,'ca-launch-v1',false)$$,'42501',null,'notice requires separate confirmation');
select lives_ok($$select public.acknowledge_policies('ca-launch-v1',true,'ca-launch-v1',true)$$,'self explicit acknowledgement');
select ok((select terms_accepted_at >= now() and privacy_notice_acknowledged_at >= now() from public.profiles where id=auth.uid()),'database timestamps');
select throws_ok($$update public.profiles set terms_accepted_at='1900-01-01' where id=auth.uid()$$,'42501',null,'REST cannot forge time');
select throws_ok($$update public.profiles set terms_version='old' where id=auth.uid()$$,'42501',null,'REST cannot rewrite version');
select lives_ok($$update public.profiles set display_name='Acknowledged' where id=auth.uid()$$,'corresponding profile edit succeeds');
select ok((select terms_accepted_at = privacy_notice_acknowledged_at from public.profiles where id=auth.uid()),'unrelated edit preserves acceptance');
reset role;
select set_config('request.jwt.claims','{}',true);
update public.profiles set terms_version='older-policy',terms_accepted_at='2020-01-01' where id='c3000000-0000-4000-8000-000000000001';
select set_config('request.jwt.claims','{"sub":"c3000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$update public.profiles set city='Old policy' where id=auth.uid()$$,'42501','policy_acknowledgement_required','existing old acceptance cannot bypass next write');
select lives_ok($$select * from public.list_seeker_applications()$$,'old acceptance does not ban history reads');
select lives_ok($$select public.acknowledge_policies('ca-launch-v1',true,'ca-launch-v1',true)$$,'old account explicitly acknowledges current terms');
select ok((select terms_accepted_at >= now() from public.profiles where id=auth.uid()),'new version receives fresh DB time');
reset role;
select set_config('request.jwt.claims','{}',true);
update public.profiles set account_status='suspended' where id='c3000000-0000-4000-8000-000000000001';
select set_config('request.jwt.claims','{"sub":"c3000000-0000-4000-8000-000000000001","role":"authenticated"}',true);
set local role authenticated;
select throws_ok($$select public.acknowledge_policies('ca-launch-v1',true,'ca-launch-v1',true)$$,'42501','account_suspended','acknowledgement cannot bypass C2 suspension');
select * from finish();
rollback;
